### PR TITLE
Added useful packages including rsync for publishing static files

### PR DESCRIPTION
**Pull request by marclennox**

### CODE REVIEW

**Comment by snocorp** [comment]
This seems like it complicates the docker container. I haven't needed any of those tools. Isn't it more appropriate to use a different container for this stuff? Or perhaps you can describe the scenario where this stuff is needed.

**Comment by marclennox** [comment]
I need rsync for a change I'm making in how the website is deployed and consumed by the nginx container.

**Comment by marclennox** [comment]
The other ones are nice to haves when you need to do debugging inside the container, but I can live without them.  Need rsync though.

**Comment by marclennox** [comment]
If you're totally against it I'll add it to the restore-website image.

**Comment by marclennox** [comment]
Although doing it in the downstream image makes for really slow builds of the website docker.

**Comment by snocorp** [comment]
I just didn't understand. I see the use case now. Will merge.

**Comment by marclennox** [comment]
Cool.  Thanks.

**Comment by asmaloney** [comment]
Just curious - why **curl** *and* **wget** - aren't they functionally equivalent?  Or are their features in one that aren't in the other?

**Comment by marclennox** [comment]
They are functionally equivalent, but I find one easier than the other depending on the particular task at hand.  I usually bake these tools into most of my base images, they come in handy when doing debugging sometimes and don’t take a lot of space…  not required though.

—

**Pull request merged**
